package com.example.apexauto.entity;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.hibernate.annotations.*;
import org.springframework.security.core.GrantedAuthority;
import org.springframework.security.core.authority.SimpleGrantedAuthority;
import org.springframework.security.core.userdetails.UserDetails;

import java.util.Collection;
import java.util.Collections;
import java.util.*;

// This is the User entity class that represents the users of the application. It contains fields for user information, authentication, and account status.

@Table(name = "users")
@Entity
@AllArgsConstructor
@NoArgsConstructor
public class User implements UserDetails {

    // The unique identifier for each user, automatically generated by the database.
    @Setter
    @Getter
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(nullable = false)
    private int userId;

    // The first name of the user, which is a required field.
    @Setter
    @Getter
    @Column(nullable = false)
    private String firstName;

    // The last name of the user, which is a required field.
    @Setter
    @Getter
    @Column(nullable = false)
    private String lastName;

    // The email address of the user, which must be unique and is a required field.
    @Setter
    @Getter
    @Column(unique = true, length = 100, nullable = false)
    private String email;

    // The password for the user's account, which is a required field.
    @Getter
    @Setter
    @Column(nullable = false)
    private String password;

    // This determines the role of the user, which can be either "USER" or "ADMIN". It is a required field.
    @Getter
    @Setter
    @Column(nullable = false)
    private String roleName;

    // A boolean field indicating whether the user's email has been verified.
    @Column(nullable = false)
    @Getter
    @Setter
    private boolean isEmailVerified;

    // The timestamp when the user account was created, automatically set by the database.
    @Setter
    @Getter
    @CreationTimestamp
    @Column(updatable = false, name = "created_at")
    private Date createdAt;

    // The timestamp when the user account was last updated, automatically set by the database.
    @Setter
    @Getter
    @UpdateTimestamp
    @Column(name = "updated_at")
    private Date updatedAt;

    // A boolean field indicating whether the user's account is enabled.
    @Column(nullable = false)
    @Getter
    @Setter
    private boolean isAccountEnabled;
    
    // The number of failed login attempts for the user's account.
    @Setter
    @Getter
    @Column
    private int failedLoginAttempts;

    // A boolean field indicating whether the user's account is locked due to too many failed login attempts.
    @Column(nullable = false)
    @Getter
    @Setter
    private boolean isAccountLocked;

    // A token used for password reset functionality, which is a required field.
    @Getter
    @Setter
    @Column(nullable = false)
    private String passwordResetToken;

    // The expiration date and time for the password reset token, which is a required field.
    @Getter
    @Setter
    @Column(nullable = false)
    private Date passwordResetTokenExpiresAt;

    // A token used for email verification.
    @Getter
    @Setter
    @Column
    private String emailVerificationToken;

    // The expiration date and time for the email verification token.
    @Getter
    @Setter
    @Column
    private Date emailVerificationTokenExpiresAt;

    // The timestamp until which an admin has temporarily restricted (blocked) this account. Null means not restricted.
    @Getter
    @Setter
    @Column(name = "restricted_until")
    private Date restrictedUntil;

    @Override
    public Collection<? extends GrantedAuthority> getAuthorities() {
        String normalizedRole = roleName == null || roleName.isBlank()
                ? "USER"
                : roleName.trim().toUpperCase(Locale.ROOT);

        String authority = normalizedRole.startsWith("ROLE_")
                ? normalizedRole
                : "ROLE_" + normalizedRole;

        return Collections.singletonList(new SimpleGrantedAuthority(authority));
    }

    @Override
    public String getUsername() {
        return email;
    }

    @Override
    public boolean isAccountNonExpired() {
        return true;
    }

    @Override
    public boolean isAccountNonLocked() {
        if (isAccountLocked) {
            return false;
        }
        return restrictedUntil == null || restrictedUntil.before(new Date());
    }

    // Convenience check used outside of Spring Security to see if an admin-imposed restriction is currently active.
    public boolean isCurrentlyRestricted() {
        return restrictedUntil != null && restrictedUntil.after(new Date());
    }

    @Override
    public boolean isCredentialsNonExpired() {
        return true;
    }

    @Override
    public boolean isEnabled() {
        return isAccountEnabled && isEmailVerified;
    }


}
