package com.example.apexauto.entity;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;
import org.hibernate.annotations.*;
import org.springframework.security.core.GrantedAuthority;
import org.springframework.security.core.authority.SimpleGrantedAuthority;
import org.springframework.security.core.userdetails.UserDetails;

import java.util.Collection;
import java.util.Collections;
import java.util.*;

// This is the User entity class that represents the users of the application. It contains fields for user information, authentication, and account status.

public class User implements UserDetails {

    // The unique identifier for each user, automatically generated by the database.
    @Setter
    @Getter
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(nullable = false)
    private int userId;

    // The first name of the user, which is a required field.
    @Setter
    @Getter
    @Column(nullable = false)
    private String firstName;

    // The last name of the user, which is a required field.
    @Setter
    @Getter
    @Column(nullable = false)
    private String lastName;

    // The email address of the user, which must be unique and is a required field.
    @Setter
    @Getter
    @Column(unique = true, length = 100, nullable = false)
    private String email;

    // The password for the user's account, which is a required field.
    @Getter
    @Setter
    @Column(nullable = false)
    private String password;

    // A boolean field indicating whether the user's email has been verified.
    @Column(nullable = false)
    @Getter
    @Setter
    private boolean isEmailVerified;

    // The timestamp when the user account was created, automatically set by the database.
    @Setter
    @Getter
    @CreationTimestamp
    @Column(updatable = false, name = "created_at")
    private Date createdAt;

    // The timestamp when the user account was last updated, automatically set by the database.
    @Setter
    @Getter
    @UpdateTimestamp
    @Column(name = "updated_at")
    private Date updatedAt;

    // A boolean field indicating whether the user's account is enabled.
    @Column(nullable = false)
    @Getter
    @Setter
    private boolean isAccountEnabled;
    
    // The number of failed login attempts for the user's account.
    @Setter
    @Getter
    @Column
    private int failedLoginAttempts;

    // A boolean field indicating whether the user's account is locked due to too many failed login attempts.
    @Column(nullable = false)
    @Getter
    @Setter
    private boolean isAccountLocked;

    // A token used for password reset functionality, which is a required field.
    @Getter
    @Setter
    @Column(nullable = false)
    private String passwordResetToken;

    // The expiration date and time for the password reset token, which is a required field.
    @Getter
    @Setter
    @Column(nullable = false)
    private Date passwordResetTokenExpiresAt;

    @Override
    public Collection<? extends GrantedAuthority> getAuthorities() {
        return Collections.singletonList(new SimpleGrantedAuthority("ROLE_USER"));
    }

    @Override
    public String getUsername() {
        return email;
    }

    @Override
    public boolean isAccountNonExpired() {
        return true;
    }

    @Override
    public boolean isAccountNonLocked() {
        return !isAccountLocked;
    }

    @Override
    public boolean isCredentialsNonExpired() {
        return true;
    }

    @Override
    public boolean isEnabled() {
        return isAccountEnabled && isEmailVerified;
    }


}
