package com.example.apexauto.entity;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@Table(name = "vehicleHistory")
@Entity
@AllArgsConstructor
@NoArgsConstructor
public class VehicleHistory {

    // The unique identifier for each vehicle history entry, automatically generated by the database.
    @Getter
    @Setter
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(nullable = false)
    private int historyId;

    // The foreign key that references the user associated with this vehicle history entry. It is a required field.
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id", nullable = false)
    @Getter
    @Setter
    private User user;

    // The foreign key relationship to the Vehicle entity, indicating which vehicle this history entry is associated with.
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "vehicle_id", nullable = false)
    @Getter
    @Setter
    private Vehicle vehicle;

    // This field contains comments or notes about the vehicle's history, such as maintenance records, accidents, etc. It is a required field.
    @Getter
    @Setter
    @Column(nullable = false)
    @GeneratedValue(strategy = GenerationType.AUTO)
    private String vehicleHistoryComments;
}
