package com.example.apexauto.entity;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.Setter;
import org.hibernate.annotations.*;

import java.util.Collection;
import java.util.Collections;
import java.util.*;

@Table(name = "vehicles")
@Entity
@AllArgsConstructor
public class Vehicle {

    // The unique identifier for each vehicle, automatically generated by the database.
    @Getter
    @Setter
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(nullable = false)
    private int vehicleId;

    // This is the brand or manufacturer of the vehicle, such as Toyota, Ford, etc. It is a required field.
    @Getter
    @Setter
    @Column(nullable = false)
    private String brand;

    // The make of the vehicle, which is a required field.
    @Getter
    @Setter
    @Column(nullable = false)
    private String make;

    // The model of the vehicle, which is a required field.
    @Setter
    @Getter
    @Column(nullable = false)
    private String model;

    // The year of the vehicle, which is a required field.
    @Getter
    @Setter
    @Column(nullable = false)
    private int year;

    // This is the color of the vehicle, which is a required field.
    @Getter
    @Setter
    @Column(nullable = false)
    private String color;

    // The number of doors the vehicle has, which is a required field.
    @Getter
    @Setter
    @Column(nullable = false)
    private int doors;

    // The number of seats in the vehicle, which is a required field.
    @Getter
    @Setter
    @Column(nullable = false)
    private int seats;

    // The emission score of the vehicle, which is a required field.
    @Getter
    @Setter
    @Column(nullable = false)
    private double emissionScore;

    // The fuel usage of the vehicle, which is a required field.
    @Getter
    @Setter
    @Column(nullable = false)
    private double fuelUsage;

    // The mileage of the vehicle, which is a required field.
    @Getter
    @Setter
    @Column(nullable = false)
    private double millage;

    // A boolean field indicating whether the vehicle is currently on sale, which is a required field.
    @Getter
    @Setter
    @Column(nullable = false)
    private boolean isOnSale;

    // A boolean field indicating whether the vehicle is currently in stock, which is a required field.
    @Getter
    @Setter
    @Column(nullable = false)
    private boolean isInStock;

    // The price of the vehicle, which is a required field.
    @Getter
    @Setter
    @Column(nullable = false)
    private double price;
}
