package com.example.apexauto.entity;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.Setter;
import org.hibernate.annotations.*;

import java.util.Collection;
import java.util.Collections;
import java.util.*;

@Table(name = "vehicles")
@Entity
@AllArgsConstructor
public class Vehicle {

    // The unique identifier for each vehicle, automatically generated by the database.
    @Getter
    @Setter
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(nullable = false)
    private int vehicleId;

    // This is the brand or manufacturer of the vehicle, such as Toyota, Ford, etc. It is a required field.
    @Getter
    @Setter
    @Column(nullable = false)
    private String brand;

    // The make of the vehicle, which is a required field.
    @Getter
    @Setter
    @Column(nullable = false)
    private String make;

    // The model of the vehicle, which is a required field.
    @Setter
    @Getter
    @Column(nullable = false)
    private String model;

    // The year of the vehicle, which is a required field.
    @Getter
    @Setter
    @Column(nullable = false)
    private int year;

    @Getter
    @Setter
    @Column(nullable = false)
    private String color;

    @Getter
    @Setter
    @Column(nullable = false)
    private int doors;

    @Getter
    @Setter
    @Column(nullable = false)
    private int seats;

    @Getter
    @Setter
    @Column(nullable = false)
    private double emissionScore;

    @Getter
    @Setter
    @Column(nullable = false)
    private double fuelUsage;

    @Getter
    @Setter
    @Column(nullable = false)
    private double millage;

    @Getter
    @Setter
    @Column(nullable = false)
    private boolean isOnSale;

    @Getter
    @Setter
    @Column(nullable = false)
    private boolean isInStock;

    @Getter
    @Setter
    @Column(nullable = false)
    private double price;
}
